[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/docs"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/commands"
  to = "/commands.html"
  status = 200

[[redirects]]
  from = "/self-hosting"
  to = "/self-hosting.html"
  status = 200

[[redirects]]
  from = "/invite"
  to = "/add-to-server.html"
  status = 200

[[redirects]]
  from = "/add-to-server"
  to = "/add-to-server.html"
  status = 200
